services:
  - type: web
    name: fastyoutubeapi
    plan : free
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn fastyoutubeapi:app --host 0.0.0.0 --port $PORT
